/**
 * Klaviyo flow teardowns for ecommerce. Each one breaks a single automated
 * flow into trigger, filters, sequence, branch logic, copy outline, what to
 * measure and common mistakes. General practice only; nothing here claims a
 * client result and there are no statistics (see scripts/quality-gate.mjs).
 */
export type FlowTeardown = {
  slug: string;
  /** The H1, e.g. "Abandoned cart flow teardown". */
  flow: string;
  metaTitle: string;
  /** 160 characters or fewer. */
  metaDescription: string;
  /** A direct answer, quotable as it stands. */
  answer: string;
  trigger: string;
  filters: string[];
  sequence: { step: string; timing: string; purpose: string }[];
  branches: string[];
  copyOutline: { email: string; outline: string }[];
  measure: string[];
  mistakes: string[];
  /** Glossary term slugs. */
  terms: string[];
  /** Service page slug. */
  service: string;
};

export const FLOW_TEARDOWNS: FlowTeardown[] = [
  {
    slug: 'welcome',
    flow: 'Welcome flow teardown',
    metaTitle: 'Welcome Flow Teardown for Klaviyo Ecommerce Stores',
    metaDescription: 'A step by step teardown of an ecommerce welcome flow in Klaviyo: trigger, filters, email order, branch logic, copy outline and the mistakes to avoid.',
    answer: 'A welcome flow introduces your store to a new subscriber in the first few days after signup. It starts when someone joins your main list, sends a short run of emails covering your story, best sellers and first order incentive, and exits anyone who buys, so a new customer never sees an offer they have already used.',
    trigger: 'Added to the main signup list or a segment of new subscribers. Use the list trigger rather than a form trigger so imports, popups and checkout opt ins all enter the same flow.',
    filters: [
      'Flow filter: has not placed an order since starting this flow',
      'Flow filter: is not already a customer, or split them into a separate thank you path',
      'Trigger filter: suppress anyone who joined through a competition if you run a separate flow for it',
      'Smart sending on, so a welcome never lands on top of a campaign sent the same day',
    ],
    sequence: [
      { step: 'Email one: welcome and incentive', timing: 'Immediately', purpose: 'Confirm the signup, deliver the code or promise, and set the tone for the brand.' },
      { step: 'Email two: brand story', timing: '1 day later', purpose: 'Say why the store exists and what makes the products different.' },
      { step: 'Email three: best sellers', timing: '2 days later', purpose: 'Show the products most people buy first, using a catalogue block.' },
      { step: 'Email four: proof and reviews', timing: '2 days later', purpose: 'Reduce doubt with customer words, delivery and returns information.' },
      { step: 'Email five: incentive reminder', timing: '3 days later', purpose: 'Remind anyone who has not bought that the offer is about to lapse.' },
    ],
    branches: [
      'Conditional split on placed order: buyers leave the flow, non buyers continue',
      'Split on signup source so popup subscribers and checkout subscribers get different openings',
      'Split on engagement: if no email has been opened or clicked by step four, send one last email and then stop',
    ],
    copyOutline: [
      { email: 'Welcome', outline: 'Thank them, give the code in plain text and a button, state what to expect from you and how often.' },
      { email: 'Story', outline: 'One short founder or brand paragraph, one image, a single link to the collection that fits the story.' },
      { email: 'Best sellers', outline: 'Three to four products with one line each on who they suit, no discount shouting.' },
      { email: 'Reminder', outline: 'A calm note that the code is still valid, plus delivery and returns reassurance.' },
    ],
    measure: [
      'Revenue per recipient for each email, to find the step that earns its place',
      'Click through rate on email one, which signals whether the incentive is landing',
      'Unsubscribe rate, to see if the sequence is too long',
      'Share of subscribers who buy before the last email',
    ],
    mistakes: [
      'Sending the offer to people who already bought',
      'Making the first email slow because of a delay or a missing exit filter',
      'Five emails that all say the same thing in different words',
      'Never revisiting the flow after the catalogue or incentive changes',
    ],
    terms: ['welcome-flow', 'flow-filter', 'smart-sending'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'abandoned-cart',
    flow: 'Abandoned cart flow teardown',
    metaTitle: 'Abandoned Cart Flow Teardown for Klaviyo Stores',
    metaDescription: 'See how a Klaviyo abandoned cart flow is built: the Added to Cart trigger, filters, timing, branches and the copy each reminder needs, with common errors.',
    answer: 'An abandoned cart flow reminds someone who added items to their basket but did not start checkout. It triggers on a cart event, waits a few hours, shows the items they left, and exits the moment they begin checkout or buy. Two or three emails usually do the job without nagging.',
    trigger: 'Added to Cart metric from your store integration. This fires before checkout starts, which is what separates it from the abandoned checkout flow.',
    filters: [
      'Flow filter: has not started checkout since starting this flow',
      'Flow filter: has not placed an order since starting this flow',
      'Trigger filter: cart contains at least one item that is in stock',
      'Trigger filter: not currently in the abandoned checkout flow',
    ],
    sequence: [
      { step: 'Email one: you left something behind', timing: 'A few hours after the cart event', purpose: 'A plain reminder with the items, quantities and a clear route back to the basket.' },
      { step: 'Email two: answer the doubts', timing: '1 day later', purpose: 'Cover delivery, returns, sizing or reviews, whatever stops people finishing.' },
      { step: 'Email three: last nudge', timing: '2 days later', purpose: 'A final reminder, with an incentive only if your margin and policy allow it.' },
      { step: 'Exit and hand over', timing: 'On checkout start or order', purpose: 'Remove the profile at once and let the abandoned checkout or post purchase flow take over.' },
    ],
    branches: [
      'Conditional split on cart value: a higher value basket gets a human, support led second email, a lower one gets reviews',
      'Split on first time versus returning customer: new buyers see trust content, repeat buyers see a simple reminder',
      'Split on whether an incentive was already used this month, so discounts are not trained',
    ],
    copyOutline: [
      { email: 'Reminder', outline: 'Short subject, dynamic list of cart items with images, one button, no discount.' },
      { email: 'Doubts', outline: 'Top three reasons people hesitate on your store, answered in a line each, with review snippets.' },
      { email: 'Last nudge', outline: 'State that the basket is not reserved, offer help by reply, add an incentive only if the split allows.' },
    ],
    measure: [
      'Recovered orders per email, not just for the flow as a whole',
      'Placed order rate for each branch of the cart value split',
      'Spam complaint and unsubscribe rate on the third email',
      'Overlap with the abandoned checkout flow, to make sure nobody receives both',
    ],
    mistakes: [
      'Leading with a discount in the very first email',
      'No exit when the person checks out, so buyers keep getting reminders',
      'Showing items that have since sold out',
      'Sending to people who never gave marketing consent',
    ],
    terms: ['abandoned-cart-flow', 'conditional-split', 'event-trigger'],
    service: 'email-flows',
  },
  {
    slug: 'browse-abandonment',
    flow: 'Browse abandonment flow teardown',
    metaTitle: 'Browse Abandonment Flow Teardown for Klaviyo',
    metaDescription: 'A teardown of a Klaviyo browse abandonment flow: the Viewed Product trigger, frequency limits, one or two emails, branch rules and what to measure.',
    answer: 'A browse abandonment flow follows up with a known visitor who viewed products but never added anything to a basket. It triggers on Active on Site or Viewed Product, waits several hours, then sends a light email featuring what they looked at. It should be gentle, short and capped so it never feels like surveillance.',
    trigger: 'Viewed Product metric for identified profiles, with a flow level frequency cap. The visitor must already be a subscriber or identified through a click or form.',
    filters: [
      'Flow filter: has not added to cart since starting this flow',
      'Flow filter: has not placed an order since starting this flow',
      'Trigger filter: product viewed is in stock and has a product image in the feed',
      'Trigger filter: not received this flow within the last few days',
    ],
    sequence: [
      { step: 'Email one: still thinking it over', timing: 'About 4 hours after the view', purpose: 'Remind them of the product and offer related options.' },
      { step: 'Email two: similar picks', timing: '2 days later', purpose: 'Only for people who clicked nothing, show alternatives from the same category.' },
      { step: 'Email three: reviews and reassurance', timing: '4 days later', purpose: 'For repeat browsers of the same item, add customer words and delivery detail.' },
      { step: 'Frequency cooldown', timing: 'A few days after the last send', purpose: 'Block re entry for a set period so persistent browsers are not emailed daily.' },
    ],
    branches: [
      'Conditional split on category viewed, so each category has a relevant opening and recommendations',
      'Split on whether the profile has bought before, so loyal customers see new arrivals rather than basics',
      'Exit if the person opens a cart or checkout event, handing them to the correct flow',
    ],
    copyOutline: [
      { email: 'Still thinking it over', outline: 'Name the product viewed, show one large image, add a short benefit line and link back to that product page.' },
      { email: 'Similar picks', outline: 'Three alternatives from the same category with one line comparing them, plus a link to the collection.' },
      { email: 'Reviews and reassurance', outline: 'Two short customer quotes, delivery and returns in a line each, and a link back to the product.' },
    ],
    measure: [
      'Click through rate against the abandoned cart flow, which should be lower and is fine',
      'Revenue per recipient, since volume is high and value per send is modest',
      'Unsubscribe rate, a warning that the cap is too loose',
      'Share of triggers that actually have a catalogue image',
    ],
    mistakes: [
      'Sending a discount, which teaches browsers to wait',
      'No frequency cap, so one person browsing daily gets daily email',
      'Triggering on category pages that do not tell you which product mattered',
      'Ignoring consent rules for tracking and identification',
    ],
    terms: ['browse-abandonment-flow', 'catalog-feed', 'smart-sending'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'post-purchase',
    flow: 'Post purchase flow teardown',
    metaTitle: 'Post Purchase Flow Teardown for Klaviyo Ecommerce',
    metaDescription: 'How to structure a Klaviyo post purchase flow: Placed Order trigger, delivery aware timing, usage tips, cross sell branches and the mistakes to avoid.',
    answer: 'A post purchase flow looks after a customer between the order and the next purchase. It triggers on Placed Order, confirms what happens next, teaches them to use the product, and later opens the door to reviews and a second order. It builds repeat revenue without sending a single discount.',
    trigger: 'Placed Order metric. Keep order confirmations in the platform transactional system and use this flow for marketing messages that follow them.',
    filters: [
      'Flow filter: order has not been refunded or cancelled',
      'Trigger filter: order contains at least one physical product, not only a gift card',
      'Flow filter: profile is not in a subscription renewal flow for the same product',
      'Smart sending off for the first message if it is genuinely service related, on for the rest',
    ],
    sequence: [
      { step: 'Email one: what happens next', timing: '1 day after the order', purpose: 'Set expectations on dispatch and delivery, and give support contact details.' },
      { step: 'Email two: how to get the most from it', timing: '3 days after delivery', purpose: 'Usage guidance, care instructions or setup tips for the exact product bought.' },
      { step: 'Email three: a small ask', timing: '7 days after delivery', purpose: 'Invite a review or photo, handled in more detail by the review request flow.' },
      { step: 'Email four: complementary products', timing: '14 days after delivery', purpose: 'Suggest items that pair with what they own.' },
    ],
    branches: [
      'Conditional split on product category so usage content matches the item',
      'Split on first order versus repeat order, with a welcome to the brand for new customers',
      'Split on order value to decide whether a concierge style note is warranted',
    ],
    copyOutline: [
      { email: 'What happens next', outline: 'Thank them, state delivery steps in order, link to tracking, give a reply to address.' },
      { email: 'Get the most from it', outline: 'Three practical tips or a short video, written for the product they bought.' },
      { email: 'Cross sell', outline: 'One sentence on why these products pair well, then three items with images.' },
    ],
    measure: [
      'Repeat purchase rate for customers who went through the flow versus a holdout group',
      'Click through rate on usage content, to see what customers value',
      'Support ticket volume related to delivery, which a good first email should lower',
      'Revenue per recipient on the cross sell step',
    ],
    mistakes: [
      'Timing from the order date when delivery takes longer, so tips arrive before the parcel',
      'Mixing a review ask and a cross sell in the same email',
      'Sending the same flow to every product',
      'Ignoring returns, so unhappy customers receive upbeat sales email',
    ],
    terms: ['post-purchase-flow', 'cross-sell-email', 'holdout-group'],
    service: 'retention-strategy',
  },
  {
    slug: 'winback',
    flow: 'Winback flow teardown',
    metaTitle: 'Winback Flow Teardown for Klaviyo Ecommerce Brands',
    metaDescription: 'A teardown of a Klaviyo winback flow: lapsed customer trigger, filters, a three email arc, branch logic by value and the errors that waste lapsed buyers.',
    answer: 'A winback flow reaches past customers who have not ordered for longer than their normal buying gap. It triggers when they enter a lapsed segment, leads with a reminder or something new, escalates gently to an incentive, and stops when they buy. It should end with a sunset decision rather than endless chasing.',
    trigger: 'Entry into a segment of customers whose last order was longer ago than your typical repurchase window, built from Placed Order metrics and a date condition.',
    filters: [
      'Flow filter: has not placed an order since starting this flow',
      'Trigger filter: has opened or clicked an email in the last several months, to protect reputation',
      'Trigger filter: is not in a replenishment or subscription flow',
      'Flow filter: not received a winback within the past year',
    ],
    sequence: [
      { step: 'Email one: we have missed you', timing: 'Immediately on entry', purpose: 'Reconnect with what is new and remind them of favourites.' },
      { step: 'Email two: what has changed', timing: '4 days later', purpose: 'Share new arrivals, improvements or a restock relevant to past purchases.' },
      { step: 'Email three: a reason to return', timing: '5 days later', purpose: 'Introduce an incentive for those who did not respond to the first two.' },
      { step: 'Email four: final goodbye', timing: '7 days later', purpose: 'Offer a preference choice or confirm they will hear less from you.' },
    ],
    branches: [
      'Conditional split on lifetime value, with a stronger incentive and a personal tone only for the best customers',
      'Split on product category last bought, so the new arrivals match their taste',
      'Split on engagement: anyone who clicks at any step gets a softer path, anyone silent goes to the sunset flow',
    ],
    copyOutline: [
      { email: 'Missed you', outline: 'Warm and short, reference the last item bought, show one new product, no hard sell.' },
      { email: 'What has changed', outline: 'Three updates such as new range, better packaging or faster delivery, with links.' },
      { email: 'Reason to return', outline: 'State the incentive, its expiry and why you are offering it, in two sentences.' },
      { email: 'Goodbye', outline: 'Honest message that you will pause emails unless they click to stay.' },
    ],
    measure: [
      'Reactivation rate: lapsed customers who purchase within the flow window',
      'Unsubscribe and complaint rate, which will be higher than other flows',
      'Revenue per recipient by branch, to justify the incentive',
      'Share who go to the sunset path at the end',
    ],
    mistakes: [
      'Defining lapsed as a fixed number of days for every product',
      'Discounting first, which trains customers to lapse deliberately',
      'Including unengaged profiles and harming sender reputation',
      'No end point, so the flow never hands over to a sunset policy',
    ],
    terms: ['winback-flow', 'sunset-policy', 'customer-lifetime-value'],
    service: 'retention-strategy',
  },
  {
    slug: 'replenishment',
    flow: 'Replenishment flow teardown',
    metaTitle: 'Replenishment Flow Teardown for Klaviyo Stores',
    metaDescription: 'Teardown of a Klaviyo replenishment flow: timing from product life, product level triggers, filters, branches and copy for consumables and repeat purchases.',
    answer: 'A replenishment flow reminds a customer to reorder just before a consumable product runs out. It triggers on Placed Order for a specific product, waits for the expected usage period, then sends a reorder email. Accurate timing and a one click route back to the same item matter more than clever copy.',
    trigger: 'Placed Order or Ordered Product, filtered to a product or collection with a known usage life. Build one flow per product family rather than one for everything.',
    filters: [
      'Flow filter: has not ordered the same product since starting this flow',
      'Trigger filter: order contains a consumable item, defined by a product tag or collection',
      'Flow filter: not subscribed to a subscription for the same product',
      'Trigger filter: order was not refunded',
    ],
    sequence: [
      { step: 'Time delay set to the product life', timing: 'Roughly the usage period minus a week', purpose: 'Wait until the customer is nearing the end, not the start.' },
      { step: 'Email one: running low?', timing: 'At the end of the delay', purpose: 'A helpful reminder with the exact product and a reorder button.' },
      { step: 'Email two: reorder with ease', timing: '4 days later', purpose: 'Introduce a bundle or subscription for people who have not reordered.' },
      { step: 'Email three: still need it?', timing: '5 days later', purpose: 'Final check, with the option to change quantity or flavour.' },
    ],
    branches: [
      'Conditional split on quantity bought, which lengthens or shortens the delay',
      'Split on whether a subscription exists on the profile, redirecting to the renewal flow',
      'Split on customer segment, with a loyalty note for repeat reorderers',
    ],
    copyOutline: [
      { email: 'Running low', outline: 'Name the product, estimate when it ends, and put a single reorder button above the fold.' },
      { email: 'Reorder with ease', outline: 'Explain the subscription or bundle in two lines, with the saving described in words, not figures.' },
      { email: 'Still need it', outline: 'Simple prompt with an option to swap size, flavour or scent.' },
    ],
    measure: [
      'Reorder rate by product, which reveals whether your delay is right',
      'Time between original and repeat order, compared with your assumption',
      'Click to order conversion on the reorder button',
      'Subscription take up from email two',
    ],
    mistakes: [
      'One delay for every product regardless of usage',
      'Sending to people who have already reordered by another route',
      'Linking to the homepage instead of the product',
      'Forgetting to adjust when pack sizes change',
    ],
    terms: ['replenishment-flow', 'predictive-analytics', 'flow-filter'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'back-in-stock',
    flow: 'Back in stock flow teardown',
    metaTitle: 'Back in Stock Flow Teardown for Klaviyo Stores',
    metaDescription: 'How a Klaviyo back in stock flow works: subscribe to alert trigger, inventory rules, send speed, branches for low stock and common setup mistakes.',
    answer: 'A back in stock flow tells a shopper the moment a product they wanted is available again. It triggers on a Subscribed to Back in Stock event, sends one fast alert when inventory returns, and optionally a second nudge if stock is limited. Speed and accurate inventory data matter far more than design.',
    trigger: 'Subscribed to Back in Stock metric, created when a shopper signs up on a sold out product page. The send is released by the inventory update.',
    filters: [
      'Flow filter: has not purchased the product since subscribing',
      'Trigger filter: variant, not just product, matches the one requested',
      'Flow filter: inventory is above a minimum threshold when sending',
      'Smart sending off, because this message is one the shopper explicitly asked for',
    ],
    sequence: [
      { step: 'Confirmation of the alert', timing: 'Immediately after signup', purpose: 'Acknowledge the request, so the shopper knows they are on the list.' },
      { step: 'Back in stock alert', timing: 'As soon as inventory returns', purpose: 'Deliver the single message they asked for with a direct link.' },
      { step: 'Limited stock nudge', timing: '1 day later', purpose: 'If still unpurchased and stock is low, say so honestly.' },
      { step: 'Alternative suggestion', timing: '3 days later', purpose: 'If the item sold out again or was not bought, suggest a close substitute.' },
    ],
    branches: [
      'Conditional split on stock level, sending the nudge only when inventory is genuinely low',
      'Split on whether the profile is a marketing subscriber, offering a signup in the alert if not',
      'Split on variant availability, suggesting another size or colour when the chosen one is gone again',
    ],
    copyOutline: [
      { email: 'Confirmation', outline: 'Short, plain note with the product image and how you will notify them.' },
      { email: 'Alert', outline: 'Lead with the product name and the word available, one button to the exact variant.' },
      { email: 'Nudge', outline: 'Honest note that stock is limited, plus similar items if it sells out.' },
    ],
    measure: [
      'Click through rate on the alert, normally the highest in your account',
      'Time between restock and send, which should be short',
      'Number of subscribers per product, which guides what to reorder from suppliers',
      'Orders from the alert versus the nudge',
    ],
    mistakes: [
      'Sending alerts before stock is actually available to buy',
      'Treating the opt in as general marketing consent',
      'Not matching the variant, so shoppers click through to a sold out size',
      'Leaving the flow live for discontinued items',
    ],
    terms: ['back-in-stock-flow', 'transactional-vs-marketing-email', 'event-trigger'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'price-drop',
    flow: 'Price drop flow teardown',
    metaTitle: 'Price Drop Flow Teardown for Klaviyo Ecommerce',
    metaDescription: 'A teardown of a Klaviyo price drop flow: price change trigger, filters, send limits, branches and copy that avoids training shoppers to wait for discounts.',
    answer: 'A price drop flow tells a shopper who showed interest in a product that its price has gone down. It triggers on a price change event for products the person viewed or saved, sends one concise alert, and exits on purchase. Used sparingly it feels helpful; used constantly it teaches people to wait.',
    trigger: 'Price Drop event, generated by a catalogue update or a custom event, matched against profiles that viewed, carted or saved the item.',
    filters: [
      'Flow filter: has not purchased the product since the price changed',
      'Trigger filter: the price reduction is meaningful, not a tiny adjustment',
      'Trigger filter: not sent a price alert in the past several days',
      'Flow filter: the item is still in stock',
    ],
    sequence: [
      { step: 'Email one: the price has dropped', timing: 'Shortly after the price change', purpose: 'Show the item, the old and new price in words and a clear button.' },
      { step: 'Email two: last chance at this price', timing: '3 days later', purpose: 'Only if the sale end date is known and the shopper has not clicked.' },
      { step: 'Check price still lower', timing: 'Before each send', purpose: 'Use a conditional split on the current price so a reversed change never sends a stale alert.' },
      { step: 'Cooldown period', timing: 'A few days after the last alert', purpose: 'Stop the same person receiving a run of alerts across several products.' },
    ],
    branches: [
      'Conditional split on how the shopper engaged: carted items get a stronger message than merely viewed ones',
      'Split on profile frequency, so people who received an alert recently are skipped',
      'Split on product margin or campaign type, so permanent price changes are handled separately from sales',
    ],
    copyOutline: [
      { email: 'Price drop', outline: 'Product image first, one line on why it dropped, no countdown theatre, a button to the product.' },
      { email: 'Last chance', outline: 'Say plainly when the price ends and what similar items cost, if relevant.' },
      { email: 'Alternative', outline: 'If the item has sold out or the price rose again, point to a comparable product with a short reason.' },
    ],
    measure: [
      'Conversion to order for each alert, compared with browse abandonment',
      'Repeat alert recipients, a sign of discount waiters',
      'Margin impact reported by finance, not just attributed revenue',
      'Unsubscribe rate on this flow',
    ],
    mistakes: [
      'Alerting on every tiny price change',
      'Reusing the flow for promotions that should be campaigns',
      'Sending to people who bought at the higher price recently',
      'Showing stale prices because the feed updates slowly',
    ],
    terms: ['catalog-feed', 'event-trigger', 'attributed-revenue'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'sunset',
    flow: 'Sunset flow teardown',
    metaTitle: 'Sunset Flow Teardown for Klaviyo Deliverability',
    metaDescription: 'A teardown of a Klaviyo sunset flow: unengaged segment trigger, filters, a last chance sequence, branch rules and how it protects sender reputation.',
    answer: 'A sunset flow handles subscribers who have stopped engaging. It triggers when a profile has not opened or clicked for a set period, sends a short re engagement attempt, and then suppresses anyone who stays silent. It protects sender reputation and keeps your reporting honest.',
    trigger: 'Entry into an unengaged segment: subscribed, with no opens or clicks for a set number of months, and no recent orders.',
    filters: [
      'Trigger filter: has not placed an order recently',
      'Trigger filter: not a VIP or subscription customer',
      'Flow filter: has not clicked an email since entering the flow',
      'Flow filter: not already suppressed or unsubscribed',
    ],
    sequence: [
      { step: 'Email one: still want to hear from us?', timing: 'Immediately on entry', purpose: 'Ask for a click to stay subscribed, with a clear and honest tone.' },
      { step: 'Email two: one more try', timing: '5 days later', purpose: 'Different subject and angle, perhaps your best content or best sellers.' },
      { step: 'Email three: final notice', timing: '5 days later', purpose: 'Explain that you will stop sending without a click.' },
      { step: 'Suppress profile', timing: '3 days later', purpose: 'Update the profile so future campaigns exclude them.' },
    ],
    branches: [
      'Conditional split on click: anyone who clicks leaves the flow and is tagged as re engaged',
      'Split on Apple Mail Privacy Protection, since opens there are unreliable and clicks should decide',
      'Split on sign up age, with newer subscribers given an extra attempt',
    ],
    copyOutline: [
      { email: 'Still interested', outline: 'Short and direct, one button labelled to stay on the list, link to preferences.' },
      { email: 'One more try', outline: 'Lead with your most useful content or best seller, without pressure.' },
      { email: 'Final notice', outline: 'State the date you will stop emailing and thank them for being a subscriber.' },
    ],
    measure: [
      'Reactivation: profiles who click and return to active',
      'Bounce rate and spam complaint rate across the whole account after the flow runs',
      'Size of the suppressed group, tracked month by month',
      'Inbox placement trends in Google Postmaster Tools',
    ],
    mistakes: [
      'Using opens alone, ignoring Apple Mail Privacy Protection',
      'Sending to unengaged people at full volume first',
      'Forgetting to suppress at the end, so nothing changes',
      'Including recent buyers who simply do not open email',
    ],
    terms: ['sunset-policy', 'apple-mail-privacy-protection', 'sender-reputation'],
    service: 'email-deliverability',
  },
  {
    slug: 'birthday',
    flow: 'Birthday flow teardown',
    metaTitle: 'Birthday Flow Teardown for Klaviyo Ecommerce Stores',
    metaDescription: 'Teardown of a Klaviyo birthday flow: date property trigger, data collection, filters, timing, gift branches and how to keep the message personal and low risk.',
    answer: 'A birthday flow sends a personal message around a customer\'s birthday, usually with a small gift. It triggers on a date property, so you need to collect birthdays first. One or two warm emails is enough, with the gift framed as a thank you rather than a sales push.',
    trigger: 'Date based trigger on a birthday profile property, set to send a set number of days before the date. Collect the property through a preference form or account page.',
    filters: [
      'Trigger filter: birthday property is present and valid',
      'Trigger filter: subscribed to marketing and not suppressed',
      'Flow filter: has not received a birthday email this year',
      'Flow filter: is not in the middle of a winback sequence, to avoid clashes',
    ],
    sequence: [
      { step: 'Email one: a gift is on the way', timing: 'A few days before the birthday', purpose: 'Deliver the gift or code with a personal note.' },
      { step: 'Email two: reminder', timing: '5 days after the first email', purpose: 'Remind anyone who has not used the gift before it ends.' },
      { step: 'Check data before sending', timing: 'At trigger time', purpose: 'A filter step confirms the date is valid and the profile is still subscribed.' },
      { step: 'Email three: belated wishes', timing: '2 weeks after the birthday', purpose: 'A light closing message for non redeemers, with the gift extended once only.' },
    ],
    branches: [
      'Conditional split on customer type, with larger gifts or early access for repeat buyers',
      'Split on whether they have ever purchased, giving non buyers a first order incentive',
      'Split on region, to respect date format and a sensible send time',
    ],
    copyOutline: [
      { email: 'Gift', outline: 'Use their first name, say happy birthday in your brand voice, present the gift and its expiry plainly.' },
      { email: 'Reminder', outline: 'A short nudge, a few product ideas, and the date the gift ends.' },
      { email: 'Belated wishes', outline: 'Warm, brief, no pressure, with one last mention of the gift and how to update preferences.' },
    ],
    measure: [
      'Redemption of the gift, split by buyer and non buyer',
      'Number of profiles with a birthday property, which limits reach',
      'Click through rate relative to other flows',
      'Opt in rate on the form that collects birthdays',
    ],
    mistakes: [
      'Collecting birthdays without explaining why',
      'Sending on the exact day when the gift needs time to be used',
      'Storing dates in inconsistent formats',
      'Making the gift so large that people enter false dates',
    ],
    terms: ['birthday-and-anniversary-flow', 'merge-tags', 'dynamic-content'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'vip-loyalty',
    flow: 'VIP loyalty flow teardown',
    metaTitle: 'VIP Loyalty Flow Teardown for Klaviyo Ecommerce',
    metaDescription: 'A teardown of a Klaviyo VIP loyalty flow: segment trigger, tier filters, recognition sequence, branch logic and perks that reward without constant discounts.',
    answer: 'A VIP loyalty flow recognises your best customers when they cross a threshold. It triggers when a profile joins a VIP segment, welcomes them with specific perks, and follows up with early access and feedback requests. The aim is to feel valued, not discounted.',
    trigger: 'Entry into a VIP segment, defined by order count, total spend or a recency frequency value score.',
    filters: [
      'Trigger filter: has been in the segment, not a one off fluke',
      'Flow filter: has not already received the VIP welcome',
      'Flow filter: is subscribed to marketing',
      'Trigger filter: no outstanding refund or support dispute',
    ],
    sequence: [
      { step: 'Email one: you are one of our best', timing: 'Soon after entering the segment', purpose: 'Welcome them to VIP and explain exactly what it means.' },
      { step: 'Email two: early access', timing: '1 week later', purpose: 'Give first look at a new range or restock.' },
      { step: 'Email three: tell us what you think', timing: '3 weeks later', purpose: 'Request a short survey or review, showing their opinion matters.' },
      { step: 'Email four: a quiet thank you', timing: '2 months later', purpose: 'A small gift or experience that is not a code.' },
    ],
    branches: [
      'Conditional split on tier, with different perks for each level',
      'Split on category affinity so early access matches their taste',
      'Exit if the profile drops out of the VIP segment, with a gentle shift to another flow',
    ],
    copyOutline: [
      { email: 'You are VIP', outline: 'State the perks as a short list, avoid jargon, sign off from a named person.' },
      { email: 'Early access', outline: 'Show the new range first, say it is not public yet, link direct.' },
      { email: 'Feedback', outline: 'One question, one link, a reason it matters.' },
    ],
    measure: [
      'Repeat order rate within the VIP group over time',
      'Segment size and churn out of it',
      'Reply rate to the feedback email',
      'Revenue per recipient compared with general campaigns',
    ],
    mistakes: [
      'Making VIP just another code',
      'Defining VIP so broadly it stops feeling special',
      'Forgetting to remove people who lapse',
      'Promising perks the team cannot deliver',
    ],
    terms: ['vip-segment', 'rfm-segmentation', 'customer-lifetime-value'],
    service: 'retention-strategy',
  },
  {
    slug: 'review-request',
    flow: 'Review request flow teardown',
    metaTitle: 'Review Request Flow Teardown for Klaviyo Stores',
    metaDescription: 'A teardown of a Klaviyo review request flow: Fulfilled Order trigger, delivery timing, filters, branches by satisfaction and copy that earns honest reviews.',
    answer: 'A review request flow asks a customer for feedback once they have had time to use the product. It triggers on Fulfilled Order, waits until after delivery, asks for a review with one tap, and sends one reminder. Good timing and an easy form matter more than the wording.',
    trigger: 'Fulfilled Order metric, or a delivered event from your shipping provider, followed by a delay that reflects how long the product takes to judge.',
    filters: [
      'Flow filter: order has not been refunded or returned',
      'Flow filter: has not already left a review for the product',
      'Trigger filter: profile has not received a review request recently',
      'Flow filter: no open support ticket on the order',
    ],
    sequence: [
      { step: 'Time delay after delivery', timing: 'About a week for simple goods, longer for things that take time to judge', purpose: 'Give the customer a chance to use the item first.' },
      { step: 'Email one: how is it going?', timing: 'At the end of the delay', purpose: 'Ask for a rating with a one click star block.' },
      { step: 'Email two: reminder', timing: '5 days later', purpose: 'A softer second request for those who did not respond.' },
      { step: 'Rating branch follow up', timing: 'Straight after a rating is given', purpose: 'Send a thank you with a public review link, or a private help message for a low score.' },
    ],
    branches: [
      'Conditional split on rating: high ratings go to the public review page, low ones go to a private support route',
      'Split on first order versus repeat, with a different opening for each',
      'Split on number of items, asking about one product rather than a long list',
    ],
    copyOutline: [
      { email: 'Ask', outline: 'Say why reviews help, give a star rating block, tell them it takes a minute.' },
      { email: 'Reminder', outline: 'A brief nudge with the product image and a thank you either way.' },
      { email: 'Thank you or help', outline: 'For good ratings, link to the public review page; for poor ones, apologise and offer a reply route to support.' },
    ],
    measure: [
      'Review completion rate per product',
      'Click through rate on the star block',
      'Volume of low ratings routed to support and how fast they are answered',
      'Review count growth on key product pages',
    ],
    mistakes: [
      'Asking before the item has arrived',
      'Offering rewards in a way that breaks platform rules or biases reviews',
      'Sending everyone, including those with returns',
      'Requesting a review and a cross sell in one email',
    ],
    terms: ['post-purchase-flow', 'conditional-split', 'dynamic-content'],
    service: 'email-flows',
  },
  {
    slug: 'cross-sell',
    flow: 'Cross sell flow teardown',
    metaTitle: 'Cross Sell Flow Teardown for Klaviyo Ecommerce',
    metaDescription: 'A teardown of a Klaviyo cross sell flow: product based trigger, filters, timing after delivery, branches by category and recommendations that feel relevant.',
    answer: 'A cross sell flow suggests products that pair with what a customer already bought. It triggers on Placed Order or Fulfilled Order for specific products, waits until they have used the item, and shows a small set of complementary items. Relevance drives results, not volume of recommendations.',
    trigger: 'Ordered Product for a defined category, with a delay after fulfilment. Build the logic around product pairs you can justify.',
    filters: [
      'Flow filter: has not bought the suggested items since the order',
      'Trigger filter: order contained a qualifying core product',
      'Flow filter: not in the post purchase review step, to avoid stacking asks',
      'Trigger filter: suggested items are in stock',
    ],
    sequence: [
      { step: 'Delay after fulfilment', timing: '10 days', purpose: 'Allow time for delivery and first use.' },
      { step: 'Email one: goes well with', timing: 'At the end of the delay', purpose: 'Present two or three items that complement the purchase.' },
      { step: 'Email two: how others use it', timing: '5 days later', purpose: 'Show a bundle or routine, using content and not a sale.' },
      { step: 'Email three: still curious', timing: '1 week later', purpose: 'Offer a free delivery threshold or small incentive for the non responders.' },
    ],
    branches: [
      'Conditional split on product category so each core product has its own pairings',
      'Split on whether the customer clicked email one, with clickers moving to a stronger prompt',
      'Split on basket size, nudging smaller orders towards the free delivery threshold',
    ],
    copyOutline: [
      { email: 'Goes well with', outline: 'Reference the original purchase, explain the pairing in one sentence, show items with images.' },
      { email: 'Routine or bundle', outline: 'Outline a simple usage routine and link the bundle.' },
      { email: 'Still curious', outline: 'Short reminder and delivery threshold information.' },
    ],
    measure: [
      'Second item attach rate for each core product',
      'Revenue per recipient against the general post purchase flow',
      'Click distribution across recommended items, to refine pairings',
      'Return rate of cross sold items',
    ],
    mistakes: [
      'Relying on automatic recommendations without checking they make sense',
      'Sending before delivery has happened',
      'Showing items the customer already owns',
      'Pushing a discount when the pairing is the real reason to buy',
    ],
    terms: ['cross-sell-email', 'dynamic-content', 'catalog-feed'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'first-purchase-thank-you',
    flow: 'First purchase thank you flow teardown',
    metaTitle: 'First Purchase Thank You Flow Teardown for Klaviyo',
    metaDescription: 'Teardown of a Klaviyo first purchase thank you flow: first order filter, personal tone, onboarding emails, branches and how it sets up the second order.',
    answer: 'A first purchase thank you flow welcomes a brand new customer after their first order. It triggers on Placed Order where the order count is one, thanks them personally, explains what to expect and introduces ways to get more from the brand. Its job is to make a second purchase feel natural.',
    trigger: 'Placed Order with a trigger filter that the customer has placed exactly one order.',
    filters: [
      'Trigger filter: order count equals one',
      'Flow filter: has not placed a second order since starting',
      'Flow filter: order not cancelled or refunded',
      'Trigger filter: subscribed to marketing, otherwise only transactional messages are sent',
    ],
    sequence: [
      { step: 'Email one: thank you from the team', timing: '1 day after the order', purpose: 'A personal note acknowledging the first purchase.' },
      { step: 'Email two: your first week', timing: '3 days after delivery', purpose: 'Onboarding tips, care instructions and support links.' },
      { step: 'Email three: meet the community', timing: '10 days after delivery', purpose: 'Show social channels, user content and ways to stay in touch.' },
      { step: 'Email four: ready for your next order', timing: '3 weeks after delivery', purpose: 'Introduce a second order reason, such as a refill or companion item.' },
    ],
    branches: [
      'Conditional split on category of the first order, so onboarding is relevant',
      'Split on whether they joined through a discount, with a non discount path for full price buyers',
      'Split on whether the customer opened the first message, trying a different email if not',
    ],
    copyOutline: [
      { email: 'Thank you', outline: 'Sent from a named person, mention the specific item, say how to reach support.' },
      { email: 'First week', outline: 'Three useful tips and a link to help content.' },
      { email: 'Community', outline: 'One social proof block, one invitation to follow or tag.' },
      { email: 'Next order', outline: 'Suggest one specific item and explain why, with delivery details.' },
    ],
    measure: [
      'Second order rate within a set window after the first',
      'Support contacts after email two',
      'Click through rate across the sequence',
      'Time between first and second order',
    ],
    mistakes: [
      'Treating it as identical to the general post purchase flow',
      'Sending an incentive to someone who just paid full price',
      'Overloading the thank you with sales blocks',
      'Forgetting to exit once the second order happens',
    ],
    terms: ['post-purchase-flow', 'customer-lifetime-value', 'cohort-analysis'],
    service: 'retention-strategy',
  },
  {
    slug: 'abandoned-checkout',
    flow: 'Abandoned checkout flow teardown',
    metaTitle: 'Abandoned Checkout Flow Teardown for Klaviyo Stores',
    metaDescription: 'A teardown of a Klaviyo abandoned checkout flow: Checkout Started trigger, shorter delays, filters against the cart flow, branches and recovery copy.',
    answer: 'An abandoned checkout flow follows up with a shopper who entered their details but did not pay. It triggers on Checkout Started, sends a fast reminder, addresses payment and delivery worries, and exits on order. It uses shorter delays than the abandoned cart flow because intent is higher.',
    trigger: 'Started Checkout metric, which means the shopper has typically provided an email address and reached the payment stage.',
    filters: [
      'Flow filter: has not placed an order since starting this flow',
      'Trigger filter: checkout has a recoverable link and items still in stock',
      'Trigger filter: not already inside the abandoned cart flow',
      'Flow filter: not received this flow in the last few days',
    ],
    sequence: [
      { step: 'Email one: you were nearly there', timing: 'About 1 hour after checkout starts', purpose: 'Return them to the checkout with items and totals visible.' },
      { step: 'Email two: need a hand?', timing: '1 day later', purpose: 'Offer help, answer shipping, payment and returns questions.' },
      { step: 'Email three: final reminder', timing: '2 days later', purpose: 'A last nudge, optionally with a small free delivery or incentive step.' },
      { step: 'Exit and hand over', timing: 'On order', purpose: 'Remove the profile as soon as an order is placed so the post purchase flow starts cleanly.' },
    ],
    branches: [
      'Conditional split on order value, so larger baskets get support led contact',
      'Split on shipping cost visible at checkout, with a delivery explanation where cost is the likely blocker',
      'Split on payment method, adding reassurance on buy now pay later or wallet options',
    ],
    copyOutline: [
      { email: 'Nearly there', outline: 'Plain subject, item list and one button straight to the saved checkout.' },
      { email: 'Need a hand', outline: 'List the common blockers with short answers and a reply address.' },
      { email: 'Final reminder', outline: 'State when the saved basket may expire, with a gentle close.' },
    ],
    measure: [
      'Recovery rate by email step',
      'Spam complaint rate, since this audience is sensitive to chasing',
      'Orders recovered from email two, to see if help content works',
      'Overlap with the cart flow',
    ],
    mistakes: [
      'Waiting a full day before email one',
      'Running cart and checkout flows with no priority between them',
      'Discounting immediately',
      'Broken checkout links that open an empty basket',
    ],
    terms: ['abandoned-cart-flow', 'smart-sending', 'transactional-vs-marketing-email'],
    service: 'email-flows',
  },
  {
    slug: 'subscription-renewal-reminder',
    flow: 'Subscription renewal reminder flow teardown',
    metaTitle: 'Subscription Renewal Reminder Flow Teardown',
    metaDescription: 'A teardown of a Klaviyo subscription renewal reminder flow: upcoming order trigger, skip and swap options, failed payment handling and branches that cut churn.',
    answer: 'A subscription renewal reminder flow warns customers before their next order ships. It triggers on an upcoming order event from the subscription platform, tells them what is coming and how to skip, swap or pause, and handles failed payments politely. Clear control reduces cancellations.',
    trigger: 'Upcoming Subscription Order event from your subscription app, sent a few days before the charge.',
    filters: [
      'Trigger filter: subscription is active and not paused',
      'Flow filter: has not already skipped or cancelled this order',
      'Trigger filter: the subscription has a valid payment method',
      'Flow filter: not in the cancellation save flow',
    ],
    sequence: [
      { step: 'Email one: your next order is coming', timing: '5 days before the charge', purpose: 'List the contents, date and price, with links to skip or edit.' },
      { step: 'Email two: order confirmed', timing: 'After the charge succeeds', purpose: 'Confirm dispatch and offer an add on item.' },
      { step: 'Email three: payment problem', timing: 'When a payment failure event fires', purpose: 'Ask to update the card with a direct secure link.' },
      { step: 'Payment retry reminder', timing: '3 days after the failure', purpose: 'A second, firmer note that the subscription will pause if the card is not updated.' },
    ],
    branches: [
      'Conditional split on subscription age, so new subscribers receive more explanation',
      'Split on skips: customers who skipped last time are offered a longer interval',
      'Split on payment failure count, escalating tone gradually',
    ],
    copyOutline: [
      { email: 'Coming up', outline: 'Show the items, date and total, with buttons to skip, swap or pause.' },
      { email: 'Confirmed', outline: 'Thank them, give delivery information, show one optional add on.' },
      { email: 'Payment problem', outline: 'Neutral and helpful, explain the issue and link to update details.' },
    ],
    measure: [
      'Skip, swap and cancel rates after the reminder, split by subscription age',
      'Payment recovery rate after email three',
      'Support tickets about unexpected charges',
      'Subscription churn over time, tracked by cohort',
    ],
    mistakes: [
      'Hiding the skip option to reduce cancellations',
      'Reminding too late for people to act',
      'Treating payment failures as marketing',
      'Using vague amounts instead of actual totals',
    ],
    terms: ['subscription-churn', 'transactional-vs-marketing-email', 'event-trigger'],
    service: 'retention-strategy',
  },
  {
    slug: 'subscription-cancellation-save',
    flow: 'Subscription cancellation save flow teardown',
    metaTitle: 'Subscription Cancellation Save Flow Teardown',
    metaDescription: 'A teardown of a Klaviyo subscription cancellation save flow: cancel event trigger, reason branches, pause and swap offers and respectful exit copy.',
    answer: 'A cancellation save flow responds when a subscriber cancels or starts to. It triggers on a cancellation event, asks why, offers the option that fits the reason, such as pause, skip, swap or a smaller plan, and accepts the decision gracefully if they still leave. It keeps trust intact.',
    trigger: 'Cancelled Subscription event, or a Started Cancellation event if your app provides one.',
    filters: [
      'Flow filter: subscription has not been reactivated since starting',
      'Trigger filter: cancellation was customer initiated, not caused by payment failure',
      'Trigger filter: profile is subscribed to email',
      'Flow filter: has not received a save offer in the last several months',
    ],
    sequence: [
      { step: 'Email one: we are sorry to see you go', timing: 'Within an hour of cancelling', purpose: 'Confirm the cancellation and ask for a reason with clickable options.' },
      { step: 'Email two: an alternative', timing: '2 days later', purpose: 'Offer the option that matches the reason chosen.' },
      { step: 'Email three: the door is open', timing: '2 weeks later', purpose: 'A low key message with an easy way to restart.' },
      { step: 'Exit to winback or sunset', timing: '2 months later', purpose: 'Move non returning customers to the winback flow or end marketing if they are unengaged.' },
    ],
    branches: [
      'Conditional split on reason: too much stock leads to pause or skip, price leads to a smaller plan, taste leads to swap',
      'Split on subscription length, with long term customers contacted personally',
      'Split on whether they clicked a reason, defaulting to a general message if not',
    ],
    copyOutline: [
      { email: 'Sorry to see you go', outline: 'Confirm cancellation, then offer four or five reason links.' },
      { email: 'Alternative', outline: 'Tailored to the reason, one clear option with one button.' },
      { email: 'Open door', outline: 'Short, no pressure, with a link to restart.' },
    ],
    measure: [
      'Save rate by reason branch',
      'Share of profiles that clicked a reason',
      'Reactivation after the final email',
      'Complaints, which signal the flow is too persistent',
    ],
    mistakes: [
      'Making cancellation harder to find',
      'Offering the same discount to every reason',
      'Continuing to market to someone who clearly left',
      'Not recording reasons for product decisions',
    ],
    terms: ['subscription-churn', 'conditional-split', 'customer-lifetime-value'],
    service: 'retention-strategy',
  },
  {
    slug: 'sample-or-quiz-follow-up',
    flow: 'Sample or quiz follow up flow teardown',
    metaTitle: 'Sample or Quiz Follow Up Flow Teardown for Klaviyo',
    metaDescription: 'A teardown of a Klaviyo sample or quiz follow up flow: quiz completion trigger, answer based branches, product match emails and timing for first purchase.',
    answer: 'A sample or quiz follow up flow turns a quiz result or a sample request into a first purchase. It triggers on quiz completion or a sample order, delivers the recommendation based on answers, and follows up once the sample has arrived. Personal relevance is its strength.',
    trigger: 'Completed Quiz event with answers stored as profile properties, or Placed Order for a sample product.',
    filters: [
      'Flow filter: has not bought a full size product since starting',
      'Trigger filter: quiz answers are present, otherwise route to a generic path',
      'Trigger filter: subscribed to marketing',
      'Flow filter: not in the main welcome flow at the same moment',
    ],
    sequence: [
      { step: 'Email one: your results', timing: 'Immediately', purpose: 'Present the match and a short reason it fits their answers.' },
      { step: 'Email two: how to try it', timing: '2 days later', purpose: 'Explain use, or for samples, when theirs will arrive and how to test it.' },
      { step: 'Email three: how did it go?', timing: '5 days after sample delivery', purpose: 'Ask for feedback and direct to the full size version.' },
      { step: 'Email four: your routine', timing: '1 week later', purpose: 'Suggest a complete set based on their results.' },
    ],
    branches: [
      'Conditional split on quiz outcome, with a different recommendation path per result',
      'Split on sample versus quiz only, so shipping information shows only where needed',
      'Split on reply or click, giving engaged people a more detailed guide',
    ],
    copyOutline: [
      { email: 'Results', outline: 'Reflect their answers back, give one primary recommendation and one backup.' },
      { email: 'How to try it', outline: 'Simple instructions and a note on what to look for.' },
      { email: 'How did it go', outline: 'One question with response buttons, then the full size link.' },
    ],
    measure: [
      'Conversion from quiz or sample to full size order',
      'Click rate per quiz outcome branch',
      'Time from sample delivery to purchase',
      'Number of quiz profiles missing answers',
    ],
    mistakes: [
      'Sending a generic result that ignores the answers',
      'Timing follow up before the sample arrives',
      'Asking for feedback with no clear next step',
      'Not storing quiz data as usable properties',
    ],
    terms: ['lead-magnet', 'dynamic-content', 'email-segmentation'],
    service: 'klaviyo-email-marketing',
  },
  {
    slug: 'high-value-order-concierge',
    flow: 'High value order concierge flow teardown',
    metaTitle: 'High Value Order Concierge Flow Teardown for Klaviyo',
    metaDescription: 'A teardown of a Klaviyo high value order concierge flow: order value trigger, personal tone, internal alerts, branches and white glove follow up.',
    answer: 'A high value order concierge flow gives big orders a personal touch. It triggers on Placed Order above a value threshold you set, sends a plain text style note from a real person, alerts your team, and checks in after delivery. It is about service, not selling, and it protects your most valuable relationships.',
    trigger: 'Placed Order with a trigger filter on order value above a chosen threshold, or a first order from a VIP segment.',
    filters: [
      'Trigger filter: order value above your threshold',
      'Flow filter: order not cancelled or refunded',
      'Flow filter: has not replied to the concierge message',
      'Trigger filter: not a wholesale or test order',
    ],
    sequence: [
      { step: 'Internal alert', timing: 'Immediately', purpose: 'Notify the team by internal email or webhook so someone can reach out personally.' },
      { step: 'Email one: thank you from a person', timing: 'A few hours after the order', purpose: 'Plain text style note introducing a named contact.' },
      { step: 'Email two: delivery check in', timing: '2 days after delivery', purpose: 'Ask whether everything arrived as expected.' },
      { step: 'Email three: feedback invitation', timing: '2 weeks later', purpose: 'Ask for views on the experience and offer help with next steps.' },
    ],
    branches: [
      'Conditional split on first versus repeat buyer, with more reassurance for first time high spenders',
      'Split on product type, such as fragile or set up needed, to add relevant guidance',
      'Split on reply received, which ends automated follow up so humans take over',
    ],
    copyOutline: [
      { email: 'Thank you', outline: 'First person, short, name the item, give a direct contact route.' },
      { email: 'Check in', outline: 'Ask one question and explain how to get help quickly.' },
      { email: 'Feedback', outline: 'Request a candid view and mention any ways to extend the relationship.' },
    ],
    measure: [
      'Reply rate to the first note',
      'Repeat order rate for concierge customers',
      'Support issues caught early by the check in',
      'Time taken by the team to respond to alerts',
    ],
    mistakes: [
      'Setting the threshold so low the flow loses its special feel',
      'Using a heavy designed template instead of a personal note',
      'Not monitoring the reply inbox',
      'Adding a sales pitch to the first message',
    ],
    terms: ['vip-segment', 'customer-lifetime-value', 'flow-filter'],
    service: 'retention-strategy',
  },
  {
    slug: 'lapsed-subscriber-reactivation',
    flow: 'Lapsed subscriber reactivation flow teardown',
    metaTitle: 'Lapsed Subscriber Reactivation Flow Teardown',
    metaDescription: 'A teardown of a Klaviyo lapsed subscriber reactivation flow for people who never bought: engagement trigger, filters, content led emails and a clean exit.',
    answer: 'A lapsed subscriber reactivation flow targets people who joined your list, may never have bought, and have gone quiet. It triggers on an engagement based segment, leads with content or a fresh reason to care, and removes anyone who does not respond. It differs from winback because there is no purchase history to lean on.',
    trigger: 'Entry into a segment of subscribers with no orders and no opens or clicks within a defined period, but who are not yet unengaged enough for suppression.',
    filters: [
      'Trigger filter: has never placed an order',
      'Trigger filter: has not clicked an email in the defined period',
      'Flow filter: has not clicked since entering the flow',
      'Flow filter: not currently in the welcome or sunset flow',
    ],
    sequence: [
      { step: 'Email one: what you might have missed', timing: 'Immediately on entry', purpose: 'Share a best of selection with new products or popular content.' },
      { step: 'Email two: a different angle', timing: '4 days later', purpose: 'Try a use case, guide or customer story rather than another product push.' },
      { step: 'Email three: first order incentive', timing: '4 days later', purpose: 'Offer a reason to try, if your policy allows it.' },
      { step: 'Email four: preferences', timing: '5 days later', purpose: 'Let them choose how often to hear from you, or leave.' },
    ],
    branches: [
      'Conditional split on signup source, tailoring content to the original reason they joined',
      'Split on any click, moving clickers to a normal welcome style path',
      'Split on lack of clicks by the end, sending those profiles to the sunset flow',
    ],
    copyOutline: [
      { email: 'Missed', outline: 'Curated three item selection with a short line each, no apology.' },
      { email: 'Different angle', outline: 'A helpful guide or story tied to why people usually join.' },
      { email: 'Incentive', outline: 'Plain statement of the offer and expiry.' },
      { email: 'Preferences', outline: 'Link to choose topics or frequency, with an easy unsubscribe.' },
    ],
    measure: [
      'Share of lapsed subscribers who click at least once',
      'First order conversion from the incentive step',
      'Impact on spam complaint and bounce rates',
      'Number moved to the sunset flow',
    ],
    mistakes: [
      'Treating never purchasers like past customers',
      'Offering a discount in every email',
      'Not handing leftover profiles to a sunset policy',
      'Reactivating too many at once and hurting sender reputation',
    ],
    terms: ['engagement-segment', 'sunset-policy', 'email-list-growth'],
    service: 'email-deliverability',
  },
];

export const getFlowTeardown = (slug: string) => FLOW_TEARDOWNS.find((f) => f.slug === slug);

/** Four other flows, preferring the neighbours in the array (two either side, wrapping), so every page gets inbound links from related flows. */
export function flowSiblings(slug: string) {
  const i = FLOW_TEARDOWNS.findIndex((f) => f.slug === slug);
  if (i < 0) return [];
  const n = FLOW_TEARDOWNS.length;
  return [1, -1, 2, -2].map((d) => FLOW_TEARDOWNS[(i + d + n) % n]).filter((x) => x.slug !== slug);
}
